In [1]:
import pandas as pd
import numpy as numpy
import matplotlib.pyplot as pyplot
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.tree import export_graphviz
import matplotlib.pyplot as plt

In [2]:
data1 = pd.read_csv('C:\\Users\\rakix\\OneDrive\\Desktop\\dataChallenge\\applicants.csv').set_index('userid')

In [3]:
data1.head(2)

school other_school  \
userid                                                                
95030aef3e970680d882f1527f549d9e  Texas A&M University          NaN   
68ad76832a913de0d62df103b3d5b807  Texas A&M University          NaN   

                                                                             majors  \
userid                                                                                
95030aef3e970680d882f1527f549d9e  ['Landscape Architecture & Urban Planning', 'P...   
68ad76832a913de0d62df103b3d5b807  ['Electrical Engineering', 'Material Science',...   

                                                      minors   age_bin  \
userid                                                                   
95030aef3e970680d882f1527f549d9e  ['Soil and Crop Sciences']  (25, 30]   
68ad76832a913de0d62df103b3d5b807                          []  (18, 20]   

                                 classification  first_generation  \
userid                                                              
95030aef3e970680d882f1527f549d9e             Ma             False   
68ad76832a913de0d62df103b3d5b807             Jr              True   

                                  datascience_experience  \
userid                                                     
95030aef3e970680d882f1527f549d9e                       2   
68ad76832a913de0d62df103b3d5b807                       2   

                                                             technology_experience  \
userid                                                                               
95030aef3e970680d882f1527f549d9e          ['Excel', 'Python', 'Tableau', 'Pandas']   
68ad76832a913de0d62df103b3d5b807  ['Excel', 'Python', 'Pandas', 'NumPy', 'MATLAB']   

                                 num_hackathons_attended  \
userid                                                     
95030aef3e970680d882f1527f549d9e                       0   
68ad76832a913de0d62df103b3d5b807                       0   

                                                               workshop_suggestions  \
userid                                                                                
95030aef3e970680d882f1527f549d9e  Python Fundamentals (Functions/Loops)\nVisuali...   
68ad76832a913de0d62df103b3d5b807  Training videos on different levels of machine...   

                                                                relavent_industries  
userid                                                                               
95030aef3e970680d882f1527f549d9e           ['consulting', 'public_policy', 'other']  
68ad76832a913de0d62df103b3d5b807  ['technology', 'education', 'healthcare', 'ins...

In [4]:
data2 = pd.read_csv('C:\\Users\\rakix\\OneDrive\\Desktop\\dataChallenge\\queries.csv').set_index('workshop')

In [5]:
data2.head(2)

query
workshop                                                  
Machine Learning Part 2/2: Applied  Using machine learning
Machine Learning Part 1/2: Theory          underlying math

In [6]:
data3 = pd.read_csv('C:\\Users\\rakix\\OneDrive\\Desktop\\dataChallenge\\bootcamp_turnout.csv').set_index('userid')

In [7]:
data3.head(10)

workshop
userid                                                                             
f48d02fd46d249ab2c37f925f405139f                           Data Science: Start Here
f48d02fd46d249ab2c37f925f405139f                      Getting a Job in Data Science
f4610ad445934181ac9982f6ba818907                            Story Telling With Data
f4610ad445934181ac9982f6ba818907  Convolutional Neural Networks & Semantic Segme...
f4610ad445934181ac9982f6ba818907                       Machine Learning: Start Here
f3784fc5a7743ebbe9bbcfd59e909c93                      Getting a Job in Data Science
f3784fc5a7743ebbe9bbcfd59e909c93                        Natural Language Processing
f0ab166097c6f21418329b3302c13a14                           Data Science: Start Here
e86097e3762488fc8a9a4405c2f0f042                           Data Science: Start Here
e86097e3762488fc8a9a4405c2f0f042                        Natural Language Processing

In [8]:
data4 = pd.read_csv('C:\\Users\\rakix\\OneDrive\\Desktop\\dataChallenge\\workshops.csv').set_index('workshop')

In [9]:
data4.head(10)

event  \
workshop                                        
Introduction to Python                TD 2020   
Storytelling with Data                TD 2020   
Stats for Data Scientists             TD 2020   
How To Win TAMU Datathon              TD 2020   
Intro to Natural Language Processing  TD 2020   
Data Wrangling                        TD 2020   
Data Visualization                    TD 2020   
Machine Learning Interpretability     TD 2020   
Intro to Neural Networks              TD 2020   
Machine Learning Part 1/2: Theory     TD 2020   

                                                                                   tags  \
workshop                                                                                  
Introduction to Python                for, loops, functions, while, logic, variables...   
Storytelling with Data                       presenting, impact, business, data science   
Stats for Data Scientists             statistics, confidence interval, testing, stat...   
How To Win TAMU Datathon                               win, advice, datathon, hackathon   
Intro to Natural Language Processing  sklearn, gensim, nltk, tfidf, TfidfVectorizer,...   
Data Wrangling                        jupyter notebook, pandas, import, packages, da...   
Data Visualization                    viz, visualization, seaborn, matplotlib, plots...   
Machine Learning Interpretability     explainability, partial dependence, LIME, cond...   
Intro to Neural Networks              neural networks, machine learning, introductio...   
Machine Learning Part 1/2: Theory     optimization, math, theory, machine learning, ...   

                                                                            description  \
workshop                                                                                  
Introduction to Python                Are you new to programming? Or do you want a r...   
Storytelling with Data                In this talk, we will describe how we use data...   
Stats for Data Scientists             In this talk, we will discuss some aspects of ...   
How To Win TAMU Datathon              Learn how to win at TAMU Datathon from last ye...   
Intro to Natural Language Processing  Interested in learning what Natural Language P...   
Data Wrangling                        Today, we'll dive into a process known as "dat...   
Data Visualization                    Today, we'll cover data visualization and the ...   
Machine Learning Interpretability     In this session on model interpretability, we ...   
Intro to Neural Networks              hidden layers, edges, nodes, backwards propaga...   
Machine Learning Part 1/2: Theory     Before you dive into some of the hot ML algori...   

                                         track  difficulty  
workshop                                                    
Introduction to Python                      CS           0  
Storytelling with Data                Industry           0  
Stats for Data Scientists                   DS           0  
How To Win TAMU Datathon              Industry           0  
Intro to Natural Language Processing        ML           2  
Data Wrangling                              DS           1  
Data Visualization                          DS           1  
Machine Learning Interpretability           ML           2  
Intro to Neural Networks                    DL           2  
Machine Learning Part 1/2: Theory           ML           1

In [10]:
joined = data1.join(data2)
joined.columns

Index(['school', 'other_school', 'majors', 'minors', 'age_bin',
       'classification', 'first_generation', 'datascience_experience',
       'technology_experience', 'num_hackathons_attended',
       'workshop_suggestions', 'relavent_industries', 'query'],
      dtype='object')

In [11]:
joined.head(10)

school  \
0003bb1d6585a9342bbb745bb52bb436                 New York University   
002314e62544dcb65e08d3483c4ffa75                Texas A&M University   
00732e4333714e18b3186a84efc7c5a7  Washington University in St. Louis   
0084482449fe55efd513ed31a09c8ef3                Texas A&M University   
0094451e8f688f5b45e9466528137d44                Texas A&M University   
00a84ee6be115dd286af149411e91bbe                Texas A&M University   
00b8592a7063cd97a01155d5d540330e         University of South Florida   
00f3a95bc2be650ce89640cc7c30bec1                Texas A&M University   
00fa667586baa5ab6e730e1f4eeb6314                Texas A&M University   
011c08999895a8a06f6e7f0e23b066b9                Texas A&M University   

                                 other_school  \
0003bb1d6585a9342bbb745bb52bb436          NaN   
002314e62544dcb65e08d3483c4ffa75          NaN   
00732e4333714e18b3186a84efc7c5a7          NaN   
0084482449fe55efd513ed31a09c8ef3          NaN   
0094451e8f688f5b45e9466528137d44          NaN   
00a84ee6be115dd286af149411e91bbe          NaN   
00b8592a7063cd97a01155d5d540330e          NaN   
00f3a95bc2be650ce89640cc7c30bec1          NaN   
00fa667586baa5ab6e730e1f4eeb6314          NaN   
011c08999895a8a06f6e7f0e23b066b9          NaN   

                                                                             majors  \
0003bb1d6585a9342bbb745bb52bb436                                          ['Other']   
002314e62544dcb65e08d3483c4ffa75                 ['Computer Science & Engineering']   
00732e4333714e18b3186a84efc7c5a7  ['Data Science & Analytics', 'Electrical Engin...   
0084482449fe55efd513ed31a09c8ef3                 ['Management Information Systems']   
0094451e8f688f5b45e9466528137d44                         ['Electrical Engineering']   
00a84ee6be115dd286af149411e91bbe                 ['Computer Science & Engineering']   
00b8592a7063cd97a01155d5d540330e                         ['Electrical Engineering']   
00f3a95bc2be650ce89640cc7c30bec1                 ['Computer Science & Engineering']   
00fa667586baa5ab6e730e1f4eeb6314                 ['Computer Science & Engineering']   
011c08999895a8a06f6e7f0e23b066b9          ['Industrial and/or Systems Engineering']   

                                                              minors  \
0003bb1d6585a9342bbb745bb52bb436  ['Computer Science & Engineering']   
002314e62544dcb65e08d3483c4ffa75                                  []   
00732e4333714e18b3186a84efc7c5a7                                  []   
0084482449fe55efd513ed31a09c8ef3                                  []   
0094451e8f688f5b45e9466528137d44                                  []   
00a84ee6be115dd286af149411e91bbe                                  []   
00b8592a7063cd97a01155d5d540330e  ['Computer Science & Engineering']   
00f3a95bc2be650ce89640cc7c30bec1                     ['Mathematics']   
00fa667586baa5ab6e730e1f4eeb6314                     ['Mathematics']   
011c08999895a8a06f6e7f0e23b066b9                                  []   

                                   age_bin classification  first_generation  \
0003bb1d6585a9342bbb745bb52bb436  (20, 22]             Sr             False   
002314e62544dcb65e08d3483c4ffa75  (18, 20]             Jr             False   
00732e4333714e18b3186a84efc7c5a7  (22, 25]             Ma             False   
0084482449fe55efd513ed31a09c8ef3  (22, 25]             Ma             False   
0094451e8f688f5b45e9466528137d44  (25, 30]            PhD             False   
00a84ee6be115dd286af149411e91bbe  (22, 25]             Ma             False   
00b8592a7063cd97a01155d5d540330e  (22, 25]            PhD             False   
00f3a95bc2be650ce89640cc7c30bec1  (18, 20]             Fr             False   
00fa667586baa5ab6e730e1f4eeb6314  (18, 20]             Jr             False   
011c08999895a8a06f6e7f0e23b066b9  (30, 50]             Jr              True   

                                  datascience_experience  \
0003bb1d6585a9342bbb745bb52bb436                

In [12]:
joined.classification.replace(to_replace=dict(Fr=0, So=1, Jr=2, Sr=3, Ma=4, PhD=5, O=6), inplace=True)

joined.head(4)

school  \
0003bb1d6585a9342bbb745bb52bb436                 New York University   
002314e62544dcb65e08d3483c4ffa75                Texas A&M University   
00732e4333714e18b3186a84efc7c5a7  Washington University in St. Louis   
0084482449fe55efd513ed31a09c8ef3                Texas A&M University   

                                 other_school  \
0003bb1d6585a9342bbb745bb52bb436          NaN   
002314e62544dcb65e08d3483c4ffa75          NaN   
00732e4333714e18b3186a84efc7c5a7          NaN   
0084482449fe55efd513ed31a09c8ef3          NaN   

                                                                             majors  \
0003bb1d6585a9342bbb745bb52bb436                                          ['Other']   
002314e62544dcb65e08d3483c4ffa75                 ['Computer Science & Engineering']   
00732e4333714e18b3186a84efc7c5a7  ['Data Science & Analytics', 'Electrical Engin...   
0084482449fe55efd513ed31a09c8ef3                 ['Management Information Systems']   

                                                              minors  \
0003bb1d6585a9342bbb745bb52bb436  ['Computer Science & Engineering']   
002314e62544dcb65e08d3483c4ffa75                                  []   
00732e4333714e18b3186a84efc7c5a7                                  []   
0084482449fe55efd513ed31a09c8ef3                                  []   

                                   age_bin  classification  first_generation  \
0003bb1d6585a9342bbb745bb52bb436  (20, 22]               3             False   
002314e62544dcb65e08d3483c4ffa75  (18, 20]               2             False   
00732e4333714e18b3186a84efc7c5a7  (22, 25]               4             False   
0084482449fe55efd513ed31a09c8ef3  (22, 25]               4             False   

                                  datascience_experience  \
0003bb1d6585a9342bbb745bb52bb436                       2   
002314e62544dcb65e08d3483c4ffa75                       1   
00732e4333714e18b3186a84efc7c5a7                       2   
0084482449fe55efd513ed31a09c8ef3                       2   

                                                              technology_experience  \
0003bb1d6585a9342bbb745bb52bb436                                                 []   
002314e62544dcb65e08d3483c4ffa75                           ['Python', 'full_stack']   
00732e4333714e18b3186a84efc7c5a7                                                 []   
0084482449fe55efd513ed31a09c8ef3  ['Excel', 'Python', 'Tableau', 'SQL', 'Pandas'...   

                                 num_hackathons_attended workshop_suggestions  \
0003bb1d6585a9342bbb745bb52bb436                     1-3                  NaN   
002314e62544dcb65e08d3483c4ffa75                     1-3                  NaN   
00732e4333714e18b3186a84efc7c5a7                       0                  NaN   
0084482449fe55efd513ed31a09c8ef3                     4-7                  NaN   

                                                                relavent_industries  \
0003bb1d6585a9342bbb745bb52bb436                                                 []   
002314e62544dcb65e08d3483c4ffa75                                                 []   
00732e4333714e18b3186a84efc7c5a7  ['technology', 'energy', 'consulting', 'finance']   
0084482449fe55efd513ed31a09c8ef3  ['technology', 'consulting', 'finance', 'educa...   

                                 query  
0003bb1d6585a9342bbb745bb52bb436   NaN  
002314e62544dcb65e08d3483c4ffa75   NaN  
00732e4333714e18b3186a84efc7c5a7   NaN  
0084482449fe55efd513ed31a09c8ef3   NaN

In [22]:
import numpy as np
h = joined['age_bin'] = joined['age_bin'].str.replace('(', '[')
list(h)
h.head(10)

0003bb1d6585a9342bbb745bb52bb436    [20, 22]
002314e62544dcb65e08d3483c4ffa75    [18, 20]
00732e4333714e18b3186a84efc7c5a7    [22, 25]
0084482449fe55efd513ed31a09c8ef3    [22, 25]
0094451e8f688f5b45e9466528137d44    [25, 30]
00a84ee6be115dd286af149411e91bbe    [22, 25]
00b8592a7063cd97a01155d5d540330e    [22, 25]
00f3a95bc2be650ce89640cc7c30bec1    [18, 20]
00fa667586baa5ab6e730e1f4eeb6314    [18, 20]
011c08999895a8a06f6e7f0e23b066b9    [30, 50]
Name: age_bin, dtype: object

In [37]:
x=joined['classification']
x = x.values.reshape(-1,1)
y=joined['age_bin']

In [38]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state   = 1)

In [39]:
clf = DecisionTreeClassifier()
clf.fit(x_train, y_train)

DecisionTreeClassifier()

In [40]:
clf = DecisionTreeClassifier()
clf.fit(x_train, y_train)

DecisionTreeClassifier()

In [41]:
y_pred = clf.predict(x_train)
pred = clf.predict(x_test)

In [42]:

print(confusion_matrix(y_test,pred))

print(classification_report(y_test,pred))

[[38 12  2  0  0  0]
 [ 5 87  8  0  0  0]
 [ 1 15 34 13  0  0]
 [ 0  5 13 35  3  0]
 [ 0  2  6 17  6  0]
 [ 0  0  4  3  4  0]]
              precision    recall  f1-score   support

    [15, 18]       0.86      0.73      0.79        52
    [18, 20]       0.72      0.87      0.79       100
    [20, 22]       0.51      0.54      0.52        63
    [22, 25]       0.51      0.62      0.56        56
    [25, 30]       0.46      0.19      0.27        31
    [30, 50]       0.00      0.00      0.00        11

    accuracy                           0.64       313
   macro avg       0.51      0.49      0.49       313
weighted avg       0.61      0.64      0.62       313



SyntaxError: invalid syntax (<ipython-input-76-c92a911b7523>, line 1)

In [57]:
# import pydotplus
# import graphviz

# dot_data = export_graphviz(clf, out_file=None, feature_names=joined.age_bin[1:8], class_names=joined.classification[1:6])
# graph = pydotplus.graph_from_dot_data(dot_data)
# g = graphviz.Source(dot_data)
# g.view()

ValueError: Length of feature_names, 7 does not match number of features, 1